### ISSUE TITLE
undefined method `downcase' for #<Hash:0x007fab1ee28d00>

### ISSUE THREAD

**Issue by notsoluckycharm** [fnando/browser#217]
## Description

Looks like recent changes to extracting the bot detection have broken dependent libraries (in my case, the ahoy gem [not a maintainer]).

## How to reproduce

install ahoy, and run rails s, any request will fail on the tracking of the user agent / bot.

## What do you expect

It to run

## What happened instead

Error screen ( attached )

## Software:

- Rails version: 4.2.5
- Browser gem version: tried 2.0.1 -> 2.0.2

## Full backtrace

```text
NoMethodError - undefined method `downcase' for #<Hash:0x007fab1ee28d00>:
  browser (2.0.1) lib/browser/bot.rb:61:in `downcased_ua'
  browser (2.0.1) lib/browser/bot.rb:53:in `block in bot_exception?'
  browser (2.0.1) lib/browser/bot.rb:53:in `bot_exception?'
  browser (2.0.1) lib/browser/bot.rb:33:in `bot?'
  browser (2.0.1) lib/browser/base.rb:47:in `bot?'
  ahoy_matey (1.2.1) lib/ahoy/stores/base_store.rb:48:in `bot?'
  ahoy_matey (1.2.1) lib/ahoy/stores/base_store.rb:38:in `exclude?'
  ahoy_matey (1.2.1) lib/ahoy/tracker.rb:124:in `exclude?'
  ahoy_matey (1.2.1) lib/ahoy/tracker.rb:29:in `track_visit'
  ahoy_matey (1.2.1) lib/ahoy/controller.rb:30:in `track_ahoy_visit'
  activesupport (4.2.5) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.5) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/builder.rb:63:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  ahoy_matey (1.2.1) lib/ahoy/engine.rb:18:in `call_with_quiet_ahoy'
  request_store (1.3.0) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

## Report

[Visit <http://user-agent.herokuapp.com> and paste the URL here]

<img width="1430" alt="screen shot 2016-03-04 at 2 03 31 pm" src="https://cloud.githubusercontent.com/assets/609341/13537242/ecc3f1d2-e211-11e5-85d8-82b86a4a26fc.png">

**Comment by fnando** [comment]
This exception happens because the constructor has changed from `Browser.new(hash)` to `Browser.new(ua, options)`, where `ua` is the user agent string and options is a hash.

Can you point me to ahoy's repository? I can make a PR fixing that.

As a workaround, you can specify the browser version on your own Gemfile, like `gem "browser", "~> 2.0.0"`.

**Comment by notsoluckycharm** [comment]
First, thanks for the quick reply! That means a lot to me. I opened the ticket ankane/ahoy#154

Yes, I got it to work with 1.1.0, looks like they've specified a minimum version so it explains why any new bundle install/updates will notice the issue with the browser >= 2.0 gem. 

Is there anything else I can help you with?

**Comment by fnando** [comment]
Just sent a [PR fixing this](ankane/ahoy#156). Let's see how it goes.

**Comment by fnando** [comment]
ahoy v1.2.2 fixes this issue. https://github.com/ankane/ahoy/commit/7ee7514de3b7d7b0e2786779cc4a4ef715152a6f
