### ISSUE TITLE
Error on device.mobile?

### ISSUE THREAD

**Issue by perkins2099** [fnando/browser#267]
## Description

```
b = Browser.new(:ua => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36", :accept_language => "en-us")

b.device.mobile?

TypeError: no implicit conversion of Hash into String
```

## What do you expect

Possible to fix?

## Software:

- Rails version: 4.2.6
- Browser gem version: 2.2

## Full backtrace

```text
[Paste full backtrace here]
TypeError: no implicit conversion of Hash into String
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/browser-2.2.0/lib/browser/device.rb:191:in `match'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/browser-2.2.0/lib/browser/device.rb:191:in `detect_mobile?'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/browser-2.2.0/lib/browser/device.rb:78:in `mobile?'
	from (irb):19
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/adam/code/TheoremReach/bin/rails:9:in `<top (required)>'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/commands/rails.rb:6:in `call'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/application.rb:185:in `block in serve'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/application.rb:156:in `fork'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/application.rb:156:in `serve'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
	from /Users/adam/.rvm/gems/ruby-2.3.1@theoremreach/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/adam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/adam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

```

**Comment by typeoneerror** [comment]
https://github.com/fnando/browser#migrating-to-v2

**Comment by fnando** [comment]
Closing this. Feel free to reopen this issue if you still need help.
